!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
grunnbok_server_url=https://etgltest.grunnbok.no/
grunnbok_brukernavn=***REMOVED***
grunnbok_passord=***REMOVED***
grunnbok_apiVersion=3.14

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
landbruksregister_url=https://www.landbruksdirektoratet.no/libservice/services/lib
landbruksregister_brukernavn=***REMOVED***
landbruksregister_passord=***REMOVED***

# LANDMÅLERREGISTER #
landmalerregister_url=https://aal-test.statkart.no/backend/matrikkel/sok/landmaalere
