!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
grunnbok_server_url=https://etgltest.grunnbok.no/
grunnbok_apiVersion=3.14

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
landbruksregister_url=https://www.landbruksdirektoratet.no/libservice/services/lib

# LANDMÅLERREGISTER #
landmalerregister_url=https://aal-test.atkv3-dev.kartverket-intern.cloud/backend/matrikkel/sok/landmaalere
