name: Build and Publish

on:
    push:
        branches:
            - '**'
    workflow_dispatch:

env:
    ARTIFACT: matrikkel-status
    MAJOR_VERSION: 5

jobs:
    calculate-version:
        name: Calculate Version
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version-string.outputs.version }}

        steps:
            -   name: Generate version string
                id: version-string
                shell: bash
                run: |
                    version="${{ env.MAJOR_VERSION }}.$(date -u '+%Y.%m.%d-%H.%M')-$(echo "${GITHUB_SHA}" | cut -c1-7)"
                    echo "version=${version}" >> "$GITHUB_OUTPUT"

    build:
        runs-on: ubuntu-latest
        needs: calculate-version
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_ACTOR: ${{ github.actor }}

        permissions:
            contents: read
            packages: write

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Sett opp JDK 17 for x64
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    architecture: x64

            -   name: Valider Gradle wrapper
                uses: gradle/actions/wrapper-validation@v4

            -   name: Prepare
                run: ./gradlew clean assemble --refresh-dependencies --profile --stacktrace -Dsuffix="${{ needs.calculate-version.outputs.version }}"

    test:
        name: Kjør tester
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_ACTOR: ${{ github.actor }}
        needs:
            - calculate-version

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Sett opp JDK 17 for x64
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    architecture: x64

            -   name: Validate Gradle wrapper
                uses: gradle/actions/wrapper-validation@v4

            -   name: Grant execute permission to Gradlew
                run: chmod +x ./gradlew

            -   name: Run tests
                run: ./gradlew check --continue --stacktrace --info -Dsuffix="${{ needs.calculate-version.outputs.version }}"

            -   name: Publish Test Report
                if: ${{ always() }}
                uses: mikepenz/action-junit-report@v5
                with:
                    report_paths: '**/build/test-results/*/*.xml'
                    check_name: Test rapport
                    annotate_only: true
                    detailed_summary: true
    publish:
        name: Publish to GitHub Packages
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_ACTOR: ${{ github.actor }}
        needs:
            - build
            - test
            - calculate-version
        #if: github.ref_name == 'master' && github.event_name == 'push'

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Sett opp JDK 17 for x64
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    architecture: x64

            -   name: Grant execute permission to Gradlew
                run: chmod +x ./gradlew

            -   name: Publish to GitHub Packages
                run: ./gradlew publish --stacktrace -Dsuffix="${{ needs.calculate-version.outputs.version }}"
